#!/bin/bash
# Trading Application Startup Script for GitHub Codespaces
# Generated by Config_Codespace.py

echo "🚀 Starting Trading Application..."
echo "================================"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check Python version
echo -e "${YELLOW}Checking Python version...${NC}"
python3 --version

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv venv
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source venv/bin/activate

# Upgrade pip
echo -e "${YELLOW}Upgrading pip...${NC}"
pip install --upgrade pip

# Install requirements
echo -e "${YELLOW}Installing requirements...${NC}"
pip install -r requirements.txt

# Initialize database if needed
if [ ! -f "./trading_system.db" ]; then
    echo -e "${YELLOW}Initializing database...${NC}"
    python database_migration.py
fi

# Start the trading system
echo -e "${GREEN}Starting Trading System...${NC}"
python hybrid_manager.py start

echo "================================"
echo -e "${GREEN}✅ Trading Application Started!${NC}"
echo -e "${GREEN}📊 Dashboard: http://localhost:5010${NC}"
echo "================================"
